import { ContentHash } from "../value-objects/content-hash";
import { LegalDocumentFactory } from "../factories/legal-document.factory";
import { IHashService } from "../services/hash.service";

/**
 * Simple test suite for Legal Domain.
 * Run with: npx tsx src/domain/legal/__tests__/legal-domain.test.ts
 */

class MockHashService implements IHashService {
  hash(content: string): string {
    // Simple deterministic "hash" for testing
    return "mock-hash-" + content.length + "-" + content.substring(0, 5);
  }
  getAlgorithm(): string {
    return "MOCK";
  }
}

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error("Assertion failed: " + message);
  }
}

async function runTests() {
  console.log("Running Legal Domain Tests...");

  // Test ContentHash
  const hash1 = ContentHash.create("12345678901234567890123456789012");
  const hash2 = ContentHash.create("12345678901234567890123456789012");
  const hash3 = ContentHash.create("09876543210987654321098765432109");

  assert(hash1.equals(hash2), "Hashes with same value should be equal");
  assert(!hash1.equals(hash3), "Hashes with different values should not be equal");
  console.log("✅ ContentHash tests passed");

  // Test LegalDocumentFactory & Entity
  const factory = new LegalDocumentFactory(new MockHashService());
  const doc = factory.create(
    "privacy-policy",
    "Privacy Policy",
    "1.0.0",
    [{ heading: "Section 1", content: "Content 1" }]
  );

  assert(doc.id.value === "privacy-policy", "ID should match");
  assert(doc.title === "Privacy Policy", "Title should match");
  assert(doc.version === "1.0.0", "Version should match");
  assert(doc.sections.length === 1, "Should have 1 section");
  assert(doc.hash.value.startsWith("mock-hash-"), "Hash should be generated by service");
  
  console.log("✅ LegalDocument tests passed");
  console.log("All tests passed! 🚀");
}

runTests().catch(err => {
  console.error("❌ Tests failed:", err);
  process.exit(1);
});
